### ISSUE TITLE
default language without url path

### ISSUE THREAD

**Issue by yuveliremil** [lostium/ssr-i18n-angular17#1]
How can we use default language without **lang** path in url? How can I configure server.ts  or proxy file ?
For example:

https://mydomain.com/        <==== for english   (without  **/en/**  path )
https://mydomain.com/de/
https://mydomain.com/fr/
https://mydomain.com/es/

**Comment by agarciar** [comment]
In our case, English is not set as the root path by default. However, this can be easily achieved with a few modifications. 

First, modify the angular.json file to set English as the root path. Next, adjust server.ts to modify publicPath and APP_BASE_HREF when the server handles English requests. Lastly, update the English path in proxy-server.mjs. Remember to set this path last. 

You can review the changes in this commit: https://github.com/lostium/ssr-i18n-angular17/commit/ac64526f8bf4476bef210a85323e5214704b33e6

**Comment by yuveliremil** [comment]
@agarciar , when I open  http://localhost:4000/de/    ,  I get below warning in command terminal:
C:\PROJECTS\ANGULAR\ssr-i18n-angular17\dist\ssr-i18n-angular17\browser\styles-5INURTSO.css

I think in must be
C:\PROJECTS\ANGULAR\ssr-i18n-angular17\dist\ssr-i18n-angular17\browser**\de\**styles-5INURTSO.css

How can I fix this issue ?

**Comment by agarciar** [comment]
We were unable to reproduce the error, try the full example in the [english-as-root](https://github.com/lostium/ssr-i18n-angular17/tree/english-as-root) branch.

In our case, it works correctly. The stylesheet loads properly both on the server and in the browser.

<img width="962" alt="image" src="https://github.com/lostium/ssr-i18n-angular17/assets/1536005/1aaf5001-c141-44b3-a1a2-54f63fc1747d">

<img width="1345" alt="image" src="https://github.com/lostium/ssr-i18n-angular17/assets/1536005/7caacca7-a161-4669-a8c0-9e111922e4c3">

**Comment by yuveliremil** [comment]
This happen when we add new routes. Please, check below fork:

https://github.com/yuveliremil/ssr-i18n-angular17/tree/bug_33

**Comment by agarciar** [comment]
Hi @yuveliremil, can you try again with the [english-as-root](https://github.com/lostium/ssr-i18n-angular17/tree/english-as-root) branch? I have fixed `server.ts`; now `browserDistFolder` always has the language at the end.

**Comment by yuveliremil** [comment]
Hi @agarciar , thanks.  It can also fixed by adding  _inlineCriticalCss: false_   in server.ts file like below:

```
  server.get('*', (req, res, next) => {
    /**
     * Discard baseUrl as we will provide it with langPath
     */
    const { protocol, originalUrl, headers } = req;
    commonEngine
      .render({
        bootstrap,
        documentFilePath: indexHtml,
        url: `${protocol}://${headers.host}${originalUrl}`,
        publicPath:
          lang !== 'en' ? browserDistFolder : browserDistFolder + langPath,
        providers: [
          { provide: APP_BASE_HREF, useValue: lang !== 'en' ? langPath : '/' },
          { provide: LOCALE_ID, useValue: lang },
          { provide: RESPONSE, useValue: res },
          { provide: REQUEST, useValue: req },
        ],
        inlineCriticalCss: false
      })
      .then((html) => res.send(html))
      .catch((err) => next(err));
  });
```

**Comment by agarciar** [comment]
Hi @yuveliremil, it's a possible solution but it hides the problem with the path. If you adjust browserDistFolder in server.ts, this error will disappear.

**Comment by yuveliremil** [comment]
@agarciar ,  please,  can you provide example with baseHref? for angular multiproject?

My app.config.ts file like below:

```
import { ApplicationConfig } from '@angular/core';
import { APP_BASE_HREF } from '@angular/common';

import { provideClientHydration } from '@angular/platform-browser';
import { provideRouter } from '@angular/router';

import { routes } from './app.routes';

export const appConfig: ApplicationConfig = {
  providers: [
    provideClientHydration(),
    provideRouter(routes),
    {provide: APP_BASE_HREF, useValue: '/ecommerce'}  
  ],
};

```

example of urls:
https://mydomain.com/ecommerce 
https://mydomain.com/ecommerce/de/
https://mydomain.com/ecommerce/fr/
https://mydomain.com/ecommerce/es/
